### ISSUE TITLE
One standard or two?

### ISSUE THREAD

**Issue by DavidSagan** [marcguetg/h5particle#1]
My thought is that there should be one standard which is a modification of the existing openPMD standard. This new standard would be version 2 to keep things backwards compatible.  I think this is preferable to having two standards which would put more work on program maintainers.

Thoughts?

**Comment by marcguetg** [comment]
We could make them overlap in most cases by including things like meshPath, particlePath and basePath even though we enforce them to have specific values. But maybe others can comment on that issue as well.

**Comment by DavidSagan** [comment]
Why not just have one standard with an openPMDextension(s) to handle all the cases?

**Comment by marcguetg** [comment]
I thought that was the idea. As far as I see it we have a few violations which would be easy to fix and a few others which might be harder. There we should decide if compability to openPMD or our (simulation code) specific needs are more important

**Comment by DavidSagan** [comment]
OK I was confused here so l will close the issue.
