### ISSUE TITLE
Only one mesh now allowed per snapshot

### ISSUE THREAD

**Issue by DavidSagan** [marcguetg/h5particle#10]
The version 1 standard has only one mesh per snapshot (iteration). Do we want to generalize things so that multiple meshes can be defined? [For particles the standard allows for multiple particle records (EG can have separate records for different species) so that for particles there is no potential problem.

**Comment by RemiLehe** [comment]
Thanks for the suggestion!
Could you specify more precisely what you mean by multiple meshes? And give an example for a typical situation in which this would be useful?

Thanks!

**Comment by jlvay** [comment]
Would having the field on a 3-D mesh and having slices on 2-D meshes, or even small 3-D "thumbnail" versions for fast exploration qualify as a use case for multiple meshes?

**Comment by DavidSagan** [comment]
@jlvay: Hmm. I had not thought about that situation but certainly multiple meshes could be used for this purpose. @RemiLehe: Two situations I thought of were storing the fields of multiple bunches in multiple meshes. Also, say, storing the self fields in one mesh and external fields in another.

**Comment by jlvay** [comment]
This also connects to the support of mesh refinement, which is also needed.

**Comment by DavidSagan** [comment]
@jlvay  @RemiLehe OK looks like multiple meshes are useful so I will put this in the draft standard and close this issue. -- Cheers, David
