### ISSUE TITLE
Compatility with openPMD

### ISSUE THREAD

**Issue by marcguetg** [marcguetg/h5particle#15]
I would like to clarify if we want to make a openPMD V2 and basically keep its basic structure or if we are also considering modifying it in a deeper way. eg: regrouping of attributes like I proposed in my initial draft, or flattening the hierarchy etc.

**Comment by DavidSagan** [comment]
Look at the drafts on the wiki and that should clarify things.

**Comment by DavidSagan** [comment]
@marcguetg And please tell me what you think.

**Comment by marcguetg** [comment]
While I think that the openPMD standard is well thought out there are a few things I consider could be altered for our specific needs. Here are two examples to this:

- Each property (with this I mean coordinate/charge/spin...) should be a self contained group containing all its necessary raw data and meta data (units/symbol/conversion factors/offset/min/max, etc) instead of some string tricks like positionOffset. Furthermore I feel like the subgroups position/momentum/etc are somehow artificial.

- I think we can get rid of data to flatten the hierarchy and remove unneeded elements, since we force a certain structure  (see Issue#9).

**Comment by DavidSagan** [comment]
> Each property (with this I mean coordinate/charge/spin...) should be a self contained group containing all its necessary raw data and meta data (units/symbol/conversion factors/offset/min/max, etc) instead of some string tricks like positionOffset. 

positionOffset is not in the V2 draft. Units, symbols and conversion factors are in the V2 draft. And I have just added min/max and phase space moments (see the extension page). Have I missed anything?

> I think we can get rid of data to flatten the hierarchy and remove unneeded elements, since we force a certain structure (see Issue#9).

Hmmm. I'm not sure what you mean here. Can you give me a concrete example?

**Comment by marcguetg** [comment]
OK, I think my confusion is gone on this point.
