### ISSUE TITLE
Proposal: Make "dataOrder" parameter optional

### ISSUE THREAD

**Issue by DavidSagan** [marcguetg/h5particle#4]
Someone correct me if I am wrong but for HDF5 storage the "dataOrder" parameter is not needed. If this is the case, there is no reason to make it mandatory.

**Comment by marcguetg** [comment]
I agree. That's why I dropped it when writing up the specs. Please reopen in case I'm missing something

**Comment by DavidSagan** [comment]
Let us leave this open until other people have had a chance to comment...

**Comment by RemiLehe** [comment]
I think I agree with this. In fact, although we included `dataOrder` in the initial openPMD standard (version 1.0.0), we later considered dropping it in future versions:
https://github.com/openPMD/openPMD-standard/issues/125

**Comment by DavidSagan** [comment]
@RemiLehe: In fact can anyone name a circumstance where **dataOrder** is actually needed?

**Comment by DavidSagan** [comment]
OK no one has commented in a decent amount of time so I am closing this.
